<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260620130521 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE spell_effect (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, target_type VARCHAR(255) NOT NULL, target_side VARCHAR(255) NOT NULL, target_mode VARCHAR(255) NOT NULL, target_rule VARCHAR(255) DEFAULT NULL, effect_type VARCHAR(255) NOT NULL, value INT NOT NULL, duration INT DEFAULT NULL, card_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EC166E74ACC9A20 ON spell_effect (card_id)');
        $this->addSql('ALTER TABLE spell_effect ADD CONSTRAINT FK_EC166E74ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE spell_effect DROP CONSTRAINT FK_EC166E74ACC9A20');
        $this->addSql('DROP TABLE spell_effect');
    }
}
