<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701132518 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE extension (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE booster ADD extension_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE booster ADD CONSTRAINT FK_EF769FAD812D5EB FOREIGN KEY (extension_id) REFERENCES extension (id)');
        $this->addSql('CREATE INDEX IDX_EF769FAD812D5EB ON booster (extension_id)');
        $this->addSql('ALTER TABLE card ADD extension_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D3812D5EB FOREIGN KEY (extension_id) REFERENCES extension (id)');
        $this->addSql('CREATE INDEX IDX_161498D3812D5EB ON card (extension_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE extension');
        $this->addSql('ALTER TABLE booster DROP CONSTRAINT FK_EF769FAD812D5EB');
        $this->addSql('DROP INDEX IDX_EF769FAD812D5EB');
        $this->addSql('ALTER TABLE booster DROP extension_id');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D3812D5EB');
        $this->addSql('DROP INDEX IDX_161498D3812D5EB');
        $this->addSql('ALTER TABLE card DROP extension_id');
    }
}
