<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260623162944 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booster (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, cost INT NOT NULL, card_count INT NOT NULL, rarity_weights JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE booster_opening (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, opened_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cards_obtained JSON NOT NULL, player_id INT NOT NULL, booster_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_254A7FE499E6F5DF ON booster_opening (player_id)');
        $this->addSql('CREATE INDEX IDX_254A7FE4F85E4930 ON booster_opening (booster_id)');
        $this->addSql('CREATE TABLE user_currency (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, balance INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_89DB6C3F99E6F5DF ON user_currency (player_id)');
        $this->addSql('ALTER TABLE booster_opening ADD CONSTRAINT FK_254A7FE499E6F5DF FOREIGN KEY (player_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booster_opening ADD CONSTRAINT FK_254A7FE4F85E4930 FOREIGN KEY (booster_id) REFERENCES booster (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_currency ADD CONSTRAINT FK_89DB6C3F99E6F5DF FOREIGN KEY (player_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card ADD rarity VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT fk_6c95d41a4acc9a20');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT fk_6c95d41aa76ed395');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT user_card_pkey');
        $this->addSql('DROP INDEX idx_6c95d41aa76ed395');
        $this->addSql('ALTER TABLE user_card ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE user_card ADD player_id INT NOT NULL');
        $this->addSql('ALTER TABLE user_card RENAME COLUMN user_id TO quantity');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT FK_6C95D41A4ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT FK_6C95D41A99E6F5DF FOREIGN KEY (player_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_6C95D41A99E6F5DF ON user_card (player_id)');
        $this->addSql('CREATE UNIQUE INDEX user_card_unique ON user_card (player_id, card_id)');
        $this->addSql('ALTER TABLE user_card ADD PRIMARY KEY (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booster_opening DROP CONSTRAINT FK_254A7FE499E6F5DF');
        $this->addSql('ALTER TABLE booster_opening DROP CONSTRAINT FK_254A7FE4F85E4930');
        $this->addSql('ALTER TABLE user_currency DROP CONSTRAINT FK_89DB6C3F99E6F5DF');
        $this->addSql('DROP TABLE booster');
        $this->addSql('DROP TABLE booster_opening');
        $this->addSql('DROP TABLE user_currency');
        $this->addSql('ALTER TABLE card DROP rarity');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT FK_6C95D41A4ACC9A20');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT FK_6C95D41A99E6F5DF');
        $this->addSql('DROP INDEX IDX_6C95D41A99E6F5DF');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT user_card_pkey');
        $this->addSql('DROP INDEX user_card_unique');
        $this->addSql('ALTER TABLE user_card ADD user_id INT NOT NULL');
        $this->addSql('ALTER TABLE user_card DROP id');
        $this->addSql('ALTER TABLE user_card DROP quantity');
        $this->addSql('ALTER TABLE user_card DROP player_id');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT fk_6c95d41a4acc9a20 FOREIGN KEY (card_id) REFERENCES card (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT fk_6c95d41aa76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_6c95d41aa76ed395 ON user_card (user_id)');
        $this->addSql('ALTER TABLE user_card ADD PRIMARY KEY (user_id, card_id)');
    }
}
